name: Limit File Size

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Lizard
        run: pip install lizard

      - name: Limit Complexity
        run: |
          # Check complexity of source and test files with a CCN limit of 30
          $HOME/.local/bin/lizard --CCN 30 src/*.cpp tests/ColorCoderTest.cpp

      - name: Check File Size
        run: |
          # Check the size of source and test files, with LOC limit enforced by lpar.sh
          $HOME/.local/bin/lizard src/*.cpp tests/ColorCoderTest.cpp | bash .github/workflows/lpar.sh 50
