name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install g++ (if needed)
      run: sudo apt-get install g++-7

    - name: build
      run: g++-7 -std=c++17 -Wall -Wextra -I src -o testchecker src/*.cpp tests/*.cpp main/*.cpp
      
    - name: run
      run: ./testchecker
