name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up g++
      uses: gcc-action/setup-gcc@v1
      with:
        gcc-version: '11' # Specify the version you need

    - name: build
      run: g++ -std=c++17 -Wall -Wextra -I src -o testchecker src/*.cpp tests/*.cpp main/*.cpp
      
    - name: run
      run: ./testchecker
