name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ -Wall -Wextra -I src -o testchecker src/*.cpp tests/*.cpp main/*.cpp
      
    - name: run tests
      run: ./testchecker
